imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Assetic Bundle
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
#        scssphp:
#            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        lessphp:
            apply_to: '\.less$'
            formatter: 'compressed'
    assets:
        jquery_js:
            inputs:
                - '@AppBundle/Resources/public/js/jquery/jquery.min.js'
                - '@AppBundle/Resources/public/js/jquery/jquery-ui.min.js'
        jquery_css:
            inputs:
                - '@AppBundle/Resources/public/css/jquery-ui/jquery-ui.css'
        jqgrid_js:
            inputs:
                - '@AppBundle/Resources/public/js/jqgrid/jquery.jqGrid.min.js'
                - '@AppBundle/Resources/public/js/jqgrid/grid.locale-ru.js'        
        jqgrid_css:
            inputs:
                - '@AppBundle/Resources/public/css/jqgrid/ui.jqgrid.css'
        shop_js:
            inputs:
                - '@AppBundle/Resources/public/js/shop/*'
        login_less:
            inputs:
                -'@AppBundle/Resources/public/styles/login/*'
